### ISSUE TITLE
Add Tailwind styles to Forgot Your Password? page

### ISSUE THREAD

**Issue by nskins** [nskins/todo#20]
This is relatively straightforward. We have a layout called `auth_form.html.heex` that is being used for the login and user registration pages already. We just need to use that layout for the "Forgot Your Password?" page. We can follow the example of either the login or registration page to see what other minor details need to change to make everything look good.

**Comment by joshalling** [comment]
I can take this one too.

**Comment by nskins** [comment]
Hey @joshalling! Just to clarify for anyone who only sees this issue (but as I also said in #18), any issues labeled `hacktoberfest` are fair game to anyone. The first to submit a correct PR gets the merge! Thanks again for the interest! 🙂

**Comment by sukalyanbisui** [comment]
assign this issue to me.
