### ISSUE TITLE
Remove the Show page for Items

### ISSUE THREAD

**Issue by nskins** [nskins/todo#23]
For an app like this, it isn't really necessary to have a whole page dedicated to showing a single item. 

- [x] Remove the routes `/items/:id` and `/items/:id/show/edit` from the router.
- [x] Delete the HEEx template for the `:show` items action. 
- [x] Remove the link from the `/items` route that links to `/items/:id`. 
- [x] Update test cases. We can probably just remove the ones that reference those parts of the code.

**Comment by ighmaZ** [comment]
@nskins ill take this issue

**Comment by nskins** [comment]
Hey @ighmaZ! Thanks for the interest! Any issues labeled `hacktoberfest` are fair game for anyone. The first to submit a correct PR gets the merge! 🙂

**Comment by ighmaZ** [comment]
will do that

**Comment by nskins** [comment]
PR #28.
