### ISSUE TITLE
Add some color to the due date field on the to-do item card

### ISSUE THREAD

**Issue by nskins** [nskins/todo#35]
We should add some color to highlight the importance of particular to-do items on the `/items` route.
- [ ] For any item due on the current day, the due date should appear orange and bold.
- [ ] For any item past due, the due date should appear red and bold.

This does not have to handle the case where the clock turns to 12am and then the colors update in real-time. Just make it so that the colors appear correctly on the initial page load. However, if I add or update an item so that it should appear orange or red, the correct color should appear immediately after submission.

**Comment by chinmaym07** [comment]
Hi @nskins 
Can I work on this ?

**Comment by nskins** [comment]
@chinmaym07 Of course! Thanks for the interest!
